WIP: remove contact page
deptagency/dept-engineering-blog-ui pull request #45
Opened 2022-05-03 14:58 UTC by cmdea

2022-05-04 19:57 UTC, nring requested changes
So much logic for adding a custom page, yeesh. Overall this looks good though!

2022-05-04 19:57 UTC, nring commented on pages/p/[pid].tsx
> -  console.log(pid);
🙏

2022-05-04 19:57 UTC, nring commented on lib/ghost.ts
> +
Nitpick: Extra space

2022-05-04 19:57 UTC, nring commented on lib/ghost.ts
> -  return 'slug:-contact'
Do you think it's worth it to keep this section but remove the `return 'slug:-contact'` in case there are future pages that we want to exclude from getting statically generated? Having a noop function feels gross but I like that it easily exposes potential functionality.

2022-05-04 19:57 UTC, nring commented on next.config.js
> + * Redirects are not supported by `next export`.
Is this hidden in the docs? Either way can we move this up to line 25 to be closer to where `async redirects()` is used.

2022-05-05 10:33 UTC, nring commented
Oh it looks like we can also remove all these packages from dependencies
```
import nodemailer from 'nodemailer'
import validator from 'email-validator'
import sanitize from 'sanitize-html'
```

2022-05-05 12:33 UTC, cmdea commented on next.config.js
> + * Redirects are not supported by `next export`.
It's not super hidden in the docs, but I thought it would be an helpful to explain why I didn't specify the redirect in `customImageLoaderOptions` and didn't want anyone to stumble if they used `next export`. I'll move it up!

2022-05-05 13:38 UTC, nring approved these changes

2022-05-05 13:38 UTC, nring commented on lib/ghost.ts
> +  return customSlugs.map(slug => `slug:-${slug}`)
💪

2022-05-05 16:23 UTC, merged