Enable careers page
deptagency/dept-engineering-blog-ui pull request #83
Opened 2022-07-25 19:18 UTC by bstein

2022-07-26 15:01 UTC, nring requested changes
This looks awesome! But I stopped early because I realized something. In our initial conversation, I sent over a link to a Framer site showing the option that should be built (https://deptengineering.framer.website/). The two designs on the Figma link were Art's initial design explorations. 

I realize that a ton of this work was particularly complicated, especially with the grid-based links to the modals (and the modal itself). Sorry for not being clearer about this! With the Framer design in mind, I think the code that goes into this will be a lot simpler.

2022-07-27 14:59 UTC, bstein commented on styles/dept.css
> +html.casper .careers-expandable-sections__left-grid,
New PR includes all styles in component files

2022-07-27 14:59 UTC, bstein commented on styles/dept.css
> +html.casper .careers-expandable-sections__section-preview-half {
Removed in new PR

2022-07-27 14:59 UTC, bstein commented on styles/dept.css
> +  padding: 48px 24px;
Removed in new PR

2022-07-27 14:59 UTC, bstein commented on components/SiteNav/components.tsx
> +          <Image alt="" src="/icons/arrow-right.svg" height="12" width="18" />
Added in new PR

2022-07-27 15:03 UTC, bstein commented on components/SiteNav/index.tsx
> +    <NavContainer showCareersNudge={showCareersNudge}>
Since NavContainer is a styled Container component, it includes both an outer and inner div. The inner div has a maximum width of 1440px as well as some padding on the left and right sides. Since all of NavContainer's children are placed inside the inner div, setting the background color on CareersPageNudge results in the purple color not going edge-to-edge. Please let me know if I didn't understand this correctly.

2022-07-27 18:52 UTC, nring commented
Closed in favor of #84

2022-07-27 18:52 UTC, closed without merging